import subprocess, time, os, pathlib, sys
from datetime import datetime

APP_DIR  = pathlib.Path(os.environ.get("FBD_APP_DIR", ".")).resolve()
THEME = sys.argv[1] if len(sys.argv) > 1 else "light"
APP_CMD  = ["python3", str(APP_DIR / "fbd_wslgui.test.py"), "--doc-mode", f"--doc-theme={THEME}"]
SENTINEL = pathlib.Path("/tmp/fbdwslgui_doc_ready.flag")
OUT_DIR  = APP_DIR / "fbdwslgui_docs_screens" / datetime.now().strftime("docmode_%Y%m%d_%H%M%S")
POLL_DELAY       = 0.1   # seconds between sentinel polls
SCREENSHOT_PAUSE = 0.4   # settle time before capture

import shutil as _shutil

if _shutil.which("import"):
    def capture(path, wid):
        if _shutil.which("xdotool") and wid:
            subprocess.run(["xdotool", "windowfocus", "--sync", str(wid)], check=False)
            subprocess.run(["xdotool", "windowraise", str(wid)], check=False)
        subprocess.run(["import", "-window", str(wid) if wid else "root",
                        "-silent", str(path)], check=False)
    print("[*] Screenshot backend: ImageMagick import -window WID")
elif _shutil.which("scrot"):
    def capture(path, wid):
        subprocess.run(["scrot", "-u", str(path)], check=False)
    print("[*] Screenshot backend: scrot -u (fallback; may capture wrong window)")
else:
    def capture(path, wid):
        print(f"  [!] No screenshot tool — run: sudo apt install imagemagick")
    print("[!] No screenshot backend available")

OUT_DIR.mkdir(parents=True, exist_ok=True)
SENTINEL.unlink(missing_ok=True)

print(f"[*] Output : {OUT_DIR}")
print(f"[*] Command: {' '.join(APP_CMD)}")
print("[*] Launching app in --doc-mode ...")
proc = subprocess.Popen(APP_CMD)

time.sleep(3)

try:
    while True:
        if SENTINEL.exists():
            payload = SENTINEL.read_text().strip()
            if payload == "DONE":
                print("[+] All tabs captured.")
                SENTINEL.unlink(missing_ok=True)
                break
            # Sentinel format: "label:wid"  (wid = X11 window ID from winfo_id())
            if ":" in payload:
                label, wid_str = payload.rsplit(":", 1)
                wid = int(wid_str) if wid_str.isdigit() else 0
            else:
                label, wid = payload, 0
            time.sleep(SCREENSHOT_PAUSE)
            out_path = OUT_DIR / f"{label}.png"
            try:
                capture(out_path, wid)
            except Exception as cap_exc:
                print(f"  [!] Capture failed ({cap_exc})")
            print(f"  [+] {out_path.name} (wid={wid})")
            SENTINEL.unlink()          # ACK — app proceeds to next tab
        else:
            time.sleep(POLL_DELAY)
finally:
    proc.terminate()

# ── Generate README ───────────────────────────────────────────────────────────
md_path = OUT_DIR / "README.md"
with open(md_path, "w") as f:
    f.write("# FBD Node Manager — UI Documentation\n\n")
    f.write("_Auto-generated by fbdwslgui_docmode_capture.sh_\n\n")

    # Group images by tab prefix to determine if both top/bottom exist
    from collections import defaultdict
    tab_shots = defaultdict(list)
    for img in OUT_DIR.glob("*.png"):
        parts = img.stem.split("_")
        tab_prefix = "_".join(parts[:2]) if parts[1].isdigit() else parts[0]
        tab_shots[tab_prefix].append(img)

    def sort_key(img):
        name = img.stem
        parts = name.split("_")
        pos = parts[-1]
        order = {"top": 0, "middle": 1, "bottom": 2}
        return ("_".join(parts[:-1]), order.get(pos, 99), name)

    for tab, imgs in tab_shots.items():
        # If both top and bottom exist, use label as-is; else, strip _top from label
        img_names = [img.stem for img in imgs]
        has_bottom = any(n.endswith("bottom") for n in img_names)
        for img in sorted(imgs, key=sort_key):
            label = img.stem
            if label.endswith("_top") and not has_bottom:
                label = label[:-4]  # remove _top
            label = label.replace("_", " ").title()
            f.write(f"## {label}\n\n![{img.name}]({img.name})\n\n")

print(f"[+] Markdown: {md_path}")